version: 3.1.2-{build}

build: false
environment:
    matrix:
        - PHP_TARGET: 5.6
          PHP_VC: 11
          PHP_MAJOR: 5
          PHP_TYPE: "Win32"
        - PHP_TARGET: 5.6
          PHP_VC: 11
          PHP_MAJOR: 5
          PHP_TYPE: "nts-Win32"
        - PHP_TARGET: 7.1
          PHP_VC: 14
          PHP_MAJOR: 7
          PHP_TYPE: "Win32"
        - PHP_TARGET: 7.1
          PHP_VC: 14
          PHP_MAJOR: 7
          PHP_TYPE: "nts-Win32"
    NO_INTERACTION: 1
    PHP_SDK: c:\php-sdk
    PHP_DEVPACK: c:\php-devpack

clone_depth: 1
clone_folder: c:\projects\phalcon

init:
    - SET PATH=C:\Program Files (x86)\MSBuild\%PHP_VC%.0\Bin;C:\Program Files\OpenSSL;C:\php;C:\php-sdk\bin;C:\php-devpack;%PATH%
    - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio %PHP_VC%.0\VC;C:\Program Files (x86)\Microsoft Visual Studio %PHP_VC%.0\VC\bin;%PATH%
    - SET ANSICON=121x90 (121x90)

cache:
    - vendor -> composer.json
    - composer.phar -> composer.json

os: Windows Server 2012 R2
platform:
    - x86
    - x64

matrix:
    fast_finish: true
    allow_failures:
        - platform: x64

install:
    # ==================================================
    - echo Setting PHP version...
    # ==================================================
    - appveyor DownloadFile http://windows.php.net/downloads/releases/sha1sum.txt
    - ps: $env:PHP_VERSION=type sha1sum.txt | where { $_ -match "php-(${env:PHP_TARGET}\.\d+)-src" } | foreach { $matches[1] }
    - ps: $env:PHP_PLATFORM="${env:PHP_SDK}\phpdev\vc${env:PHP_VC}\${env:PLATFORM}"
    - ps: $env:PHP_SRC="${env:PHP_PLATFORM}\php-${env:PHP_VERSION}-src"
    - ps: >-
        If ($env:PLATFORM -eq 'x86') {
            If ($env:PHP_TYPE -Match "nts-Win32") {
                $env:RELEASE_FOLDER="Release"
                $env:PHP_CONFIGURE_FLAGS="--disable-all --enable-cli --enable-phalcon=shared --enable-pdo --disable-zts"
            } Else {
                $env:RELEASE_FOLDER="Release_TS"
                $env:PHP_CONFIGURE_FLAGS="--disable-all --enable-cli --enable-phalcon=shared --enable-pdo"
            }
        } else {
            If ($env:PHP_TYPE -Match "nts-Win32") {
                $env:RELEASE_FOLDER="x64\Release"
                $env:PHP_CONFIGURE_FLAGS="--disable-all --enable-cli --enable-phalcon=shared --enable-pdo --disable-zts"
            } Else {
                $env:RELEASE_FOLDER="x64\Release_TS"
                $env:PHP_CONFIGURE_FLAGS="--disable-all --enable-cli --enable-phalcon=shared --enable-pdo"
            }
        }
        If ($env:PHP_VC -eq '11') {
            $env:VSCOMNTOOLS=$env:VS110COMNTOOLS
        } Elseif ($env:PHP_VC -eq '14') {
            $env:VSCOMNTOOLS=$env:VS140COMNTOOLS
        }
        If ($env:PLATFORM -eq 'x64') {
            $env:ARCH='x86_amd64'
            $env:PHALCON_ARCH="64"
        } Else {
            $env:ARCH='x86'
            $env:PHALCON_ARCH="32"
        }
        If ($env:PHP_TARGET -eq '5.5') {
            $env:PHP_DEPS_URL="http://windows.php.net/downloads/php-sdk/archives/deps-${env:PHP_TARGET}-vc${env:PHP_VC}-${env:PLATFORM}.7z"
        } Else {
            $env:PHP_DEPS_URL="http://windows.php.net/downloads/php-sdk/deps-${env:PHP_TARGET}-vc${env:PHP_VC}-${env:PLATFORM}.7z"
        }
        If ($env:PHP_TYPE -Match "nts-Win32") {
            $env:RELEASE_ZIPBALL="phalcon_${env:PLATFORM}_vc${env:PHP_VC}_php${env:PHP_TARGET}-nts_${env:APPVEYOR_BUILD_VERSION}"
        } Else {
            $env:RELEASE_ZIPBALL="phalcon_${env:PLATFORM}_vc${env:PHP_VC}_php${env:PHP_TARGET}_${env:APPVEYOR_BUILD_VERSION}"
        }

    # ==================================================
    - echo Initializing Build
    # ==================================================
    - mkdir %PHP_SDK% && cd %PHP_SDK%
    - ps: (new-object net.webclient).DownloadFile('http://windows.php.net/downloads/php-sdk/php-sdk-binary-tools-20110915.zip', 'C:\php-sdk.zip')
    - 7z.exe x C:\php-sdk.zip | FIND /V "ing  "
    - phpsdk_buildtree phpdev
    - ps: Rename-Item ${env:PHP_SDK}\phpdev\vc9 ${env:PHP_SDK}\phpdev\vc${env:PHP_VC}
    - mkdir %PHP_SRC%
    # ==================================================
    - echo Install PHP Dev pack
    # ==================================================
    - cd C:\
    - ps: (new-object net.webclient).DownloadFile('http://windows.php.net/downloads/releases/php-devel-pack-' + ${env:PHP_VERSION} + '-Win32-VC' + ${env:PHP_VC} + '-' + ${env:PLATFORM} + '.zip', 'C:\php-dev.zip')
    - 7z.exe x php-dev.zip | FIND /V "ing  "
    - ps: Rename-Item "php-${env:PHP_VERSION}-devel-VC${env:PHP_VC}-${env:PLATFORM}" C:\php-devpack
    # ==================================================
    - echo Downloading and preparing PHP source code
    # ==================================================
    - git clone -b PHP-%PHP_TARGET% --depth 1 https://github.com/php/php-src %PHP_SRC%
    - cd %PHP_PLATFORM%
    - ps: (new-object net.webclient).DownloadFile(${env:PHP_DEPS_URL}, 'C:\php-sdk-deps.7z')
    - 7z.exe x C:\php-sdk-deps.7z | FIND /V "ing  "
    - cd %PHP_SDK%
    - phpsdk_setvars
    - '"%VSCOMNTOOLS%\VsDevCmd" %PLATFORM%'
    - vcvarsall %ARCH%
    # ==================================================
    - echo Preparing extension to build
    # ==================================================
    - mkdir %PHP_SRC%\ext\phalcon
    - xcopy /s /q %APPVEYOR_BUILD_FOLDER%\ext\*.* %PHP_SRC%\ext\phalcon
    # ==================================================
    - echo Build PHP with enabled Phalcon
    # ==================================================
    - cd %PHP_SRC%
    - buildconf
    - configure %PHP_CONFIGURE_FLAGS%
    - nmake 2> compile-errors.log 1> compile.log
    - echo extension=%PHP_SRC%\%RELEASE_FOLDER%\php_phalcon.dll >> C:\Windows\php.ini
    - SET PATH=%PHP_SRC%\%RELEASE_FOLDER%;%PATH%
    - php -v
    - php --ri "phalcon"
    # ==================================================
    - echo Download tests dependencies...
    # ==================================================
    - cd %APPVEYOR_BUILD_FOLDER%
    - if not exist vendor (php -r "readfile('https://getcomposer.org/installer');" | php && php composer.phar --version)
    - if not exist vendor (php composer.phar update --quiet --no-ansi --no-interaction --no-progress --optimize-autoloader --dev --prefer-dist --no-suggest --ignore-platform-reqs)

build_script:
    # ==================================================
    - echo Creating package to zip
    # ==================================================
    - mkdir %APPVEYOR_BUILD_FOLDER%\package
    - cd %APPVEYOR_BUILD_FOLDER%\package
    # dll
    - cp %PHP_SRC%\%RELEASE_FOLDER%\php_phalcon.dll .\
    # docs
    # TODO

after_build:
    # ==================================================
    - echo Collect artifacts and zip
    # ==================================================
    - cd %APPVEYOR_BUILD_FOLDER%\package
    - 7z a %RELEASE_ZIPBALL%.zip *.*
    - mv %RELEASE_ZIPBALL%.zip %APPVEYOR_BUILD_FOLDER%\

on_failure:
    - 'dir'
    - ps: >-
        If (Test-Path -Path ${env:PHP_SRC}\compile-errors.log) {
            type ${env:PHP_SRC}\compile-errors.log
        }

        If (Test-Path -Path ${env:PHP_SRC}\compile.log) {
            type ${env:PHP_SRC}\compile.log
        }

on_success:
    - 'dir'
    - 'dir %PHP_SRC%\%RELEASE_FOLDER%'

artifacts:
    - path: '.\*.zip'
      type: zip
      name: Phalcon

notifications:
    - provider: Email
      to:
        - build@phalconphp.com
      subject: "Build Phalcon [{{status}}]"
      on_build_status_changed: true
